# Generated by Django 4.2.27 on 2025-12-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-role', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Team member photo', null=True, upload_to='team_photos/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Core Committee Member', 'Core Committee Member'), ('Committee Member', 'Committee Member'), ('Web Team Member', 'Web Team Member'), ('Design Team Member', 'Design Team Member')], max_length=100),
        ),
    ]
