# Generated by Django 4.2.27 on 2025-12-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teammember_options_teammember_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.AddField(
            model_name='teammember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Event Head', 'Event Head'), ('Management Head', 'Management Head'), ('Secretary', 'Secretary'), ('Core Committee Member', 'Core Committee Member'), ('Coordinator', 'Coordinator'), ('Design Team Member', 'Design Team Member'), ('Committee Member', 'Committee Member')], max_length=50),
        ),
    ]
